### ISSUE TITLE
如何使用电脑控制Android设备桌面

### ISSUE THREAD

**Issue by WillWolfWang** [andr2000/android-vncserver#1]
你好，我可以成功将项目编译成 apk 并安装到 Android 设备上，点击开启按钮后，通知栏也显示 vnc server start，我在电脑安装 vnc 客户端，却无法成功连接上 Android 设备，请问您能指导一下如何使用电脑的 vnc 客户端连接上装有该 apk 的 Android 设备么？

**Comment by andr2000** [comment]
Please re-open the issue and use English.
Thank you
